#!/bin/bash

[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }

set -e

rm -f ubuntu.iso

source fetch_build.conf

if command -v axel 2> /dev/null; then
		[ -z "$DOWNLOAD_ISO" ] && axel -o ubuntu.iso "https://releases.ubuntu.com/$CODENAME/ubuntu-$RELEASE-desktop-$ARCH.iso" || axel -o ubuntu.iso "$DOWNLOAD_ISO"
	else
		[ -z "$DOWNLOAD_ISO" ] && wget -O ubuntu.iso "https://releases.ubuntu.com/$CODENAME/ubuntu-$RELEASE-desktop-$ARCH.iso" || wget -O ubuntu.iso "$DOWNLOAD_ISO"
	fi

sudo make build.iso
