#!/bin/bash

[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }

set -e

rm -f ubuntu.iso

source fetch_build.conf

[ -z "$DOWNLOAD_ISO" ] && wget -q -O ubuntu.iso "https://releases.ubuntu.com/$CODENAME/ubuntu-$RELEASE-desktop-$ARCH.iso" || wget -q -O ubuntu.iso "$DOWNLOAD_ISO"

sudo make build.iso
